### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Zeemeuw** [K1ngl3Y/Spectral-Scream-Cheat#1]
Hello, if possible, can you upload an old version of the DLL? My game version is still stuck at 1.0.9

**Comment by K1ngl3Y** [comment]
> Hello, if possible, can you upload an old version of the DLL? My game version is still stuck at 1.0.9

Hello!

Unfortunately, I have not created a cheat for this version of the game and do not plan to do so, since the cheat is aimed exclusively at the Steam version. I do not develop for hacked versions of the game.

**Comment by Zeemeuw** [comment]
Okay, thank you, bro.
